In [36]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

In [37]:
df = pd.read_csv("KG_Obesity_Artifact/KG_Obesity_Cleaned.csv")
df.head()

,Female,Age,Height,Weight,Family_History,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_Level
0,1,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,3,3,1
1,1,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,2,3,1
2,0,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,1,3,1
3,0,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,1,4,5
4,0,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,6

In [38]:
X = df.drop('Obesity_Level', axis = 1)
Y = df['Obesity_Level']

X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.2, random_state=42, stratify=Y)

In [39]:
rf_model_1 = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model_1.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [40]:
y_pred = rf_model_1.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(rf_model_1.feature_names_in_) 
pd.Series(rf_model_1.feature_importances_, index=rf_model_1.feature_names_in_).sort_values(ascending=False)

Accuracy: 0.9545454545454546
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        53
           1       0.86      0.95      0.90        57
           2       1.00      0.97      0.99        70
           3       0.98      1.00      0.99        60
           4       1.00      0.98      0.99        65
           5       0.89      0.91      0.90        55
           6       0.95      0.91      0.93        58

    accuracy                           0.95       418
   macro avg       0.95      0.95      0.95       418
weighted avg       0.96      0.95      0.96       418

['Female' 'Age' 'Height' 'Weight' 'Family_History' 'FAVC' 'FCVC' 'NCP'
 'CAEC' 'SMOKE' 'CH2O' 'SCC' 'FAF' 'TUE' 'CALC' 'MTRANS']

Weight            0.345980
Height            0.099368
Age               0.093166
FCVC              0.088106
Female            0.059794
NCP               0.051350
TUE               0.043547
FAF               0.043028
CH2O              0.039329
Family_History    0.032865
CALC              0.030758
CAEC              0.029215
MTRANS            0.018617
FAVC              0.016968
SCC               0.005558
SMOKE             0.002351
dtype: float64

In [41]:
X2 = df.drop(columns = ['Height', 'Weight', 'Obesity_Level'], axis = 1)
Y2 = df['Obesity_Level']

X2_train, X2_test, y2_train, y2_test = train_test_split( X2, Y2, test_size=0.2, random_state=42, stratify=Y2)

In [42]:
rf_model_2 = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model_2.fit(X2_train, y2_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [43]:
y2_pred = rf_model_2.predict(X2_test)
print("Accuracy:", accuracy_score(y2_test, y2_pred))
print(classification_report(y2_test, y2_pred))
print(rf_model_2.feature_names_in_) 
pd.Series(rf_model_2.feature_importances_, index=rf_model_2.feature_names_in_).sort_values(ascending=False)

Accuracy: 0.8660287081339713
              precision    recall  f1-score   support

           0       0.88      0.94      0.91        53
           1       0.67      0.75      0.71        57
           2       0.88      0.90      0.89        70
           3       0.92      0.97      0.94        60
           4       1.00      0.98      0.99        65
           5       0.84      0.76      0.80        55
           6       0.88      0.72      0.79        58

    accuracy                           0.87       418
   macro avg       0.87      0.86      0.86       418
weighted avg       0.87      0.87      0.87       418

['Female' 'Age' 'Family_History' 'FAVC' 'FCVC' 'NCP' 'CAEC' 'SMOKE' 'CH2O'
 'SCC' 'FAF' 'TUE' 'CALC' 'MTRANS']

Age               0.164159
FCVC              0.137801
FAF               0.098432
NCP               0.098144
TUE               0.096300
CH2O              0.093509
Female            0.069064
CALC              0.054667
CAEC              0.052488
Family_History    0.050763
MTRANS            0.040231
FAVC              0.027564
SCC               0.011845
SMOKE             0.005030
dtype: float64

In [44]:
df['BMI'] = df['Weight'] / (df['Height'] ** 2)
df.head()

,Female,Age,Height,Weight,Family_History,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_Level,BMI
0,1,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,3,3,1,24.386526
1,1,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,2,3,1,24.238227
2,0,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,1,3,1,23.765432
3,0,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,1,4,5,26.851852
4,0,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,6,28.342381

In [45]:
df = df[['Female', 'Age', 'BMI', 'Height', 'Weight', 'Family_History', 'FAVC', 'FCVC',
       'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS',
       'Obesity_Level']]
df.head()

,Female,Age,BMI,Height,Weight,Family_History,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity_Level
0,1,21.0,24.386526,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,3,3,1
1,1,21.0,24.238227,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,2,3,1
2,0,23.0,23.765432,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,1,3,1
3,0,27.0,26.851852,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,1,4,5
4,0,22.0,28.342381,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,2,3,6

In [46]:
X3 = df.drop(columns = ['Height', 'Weight', 'Obesity_Level'], axis = 1)
Y3 = df['Obesity_Level']

X3_train, X3_test, y3_train, y3_test = train_test_split( X3, Y3, test_size=0.2, random_state=42, stratify=Y3)

In [47]:
rf_model_3 = RandomForestClassifier(n_estimators=200, random_state=42)
rf_model_3.fit(X3_train, y3_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [48]:
y3_pred = rf_model_3.predict(X3_test)
print("Accuracy:", accuracy_score(y3_test, y3_pred))
print(classification_report(y3_test, y3_pred))
print(rf_model_3.feature_names_in_) 
pd.Series(rf_model_3.feature_importances_, index=rf_model_3.feature_names_in_).sort_values(ascending=False)

Accuracy: 0.9856459330143541
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        53
           1       0.95      1.00      0.97        57
           2       1.00      1.00      1.00        70
           3       0.98      1.00      0.99        60
           4       1.00      0.98      0.99        65
           5       0.98      0.98      0.98        55
           6       0.98      0.97      0.97        58

    accuracy                           0.99       418
   macro avg       0.99      0.98      0.98       418
weighted avg       0.99      0.99      0.99       418

['Female' 'Age' 'BMI' 'Family_History' 'FAVC' 'FCVC' 'NCP' 'CAEC' 'SMOKE'
 'CH2O' 'SCC' 'FAF' 'TUE' 'CALC' 'MTRANS']

BMI               0.454058
FCVC              0.087656
Age               0.085214
NCP               0.052783
Female            0.048375
FAF               0.046051
CH2O              0.045359
TUE               0.041047
Family_History    0.033291
CAEC              0.031639
CALC              0.028841
MTRANS            0.019989
FAVC              0.016083
SCC               0.006934
SMOKE             0.002678
dtype: float64

In [49]:
joblib.dump(rf_model_3, "KG_Obesity_Artifact/KG_Obesity_Predictor.joblib")

['KG_Obesity_Artifact/KG_Obesity_Predictor.joblib']